### ISSUE TITLE
Plugin breaks library with type: module field in package.json

### ISSUE THREAD

**Issue by dvakatsiienko** [qmhc/vite-plugin-dts#122]
# Given

**vite-plugin-dts** version: **1.6.3**
**vite** version: **3.1.4**

**package.json**:
```json
{
  "name" : "my-lib",
  "type": "module",
  ...
}
```

**vite.config.ts**:
```ts
// imports

export default defineConfig({
  // other configs
  plugins: [dts({ config })]
})
```

**An error**:
```sh
failed to load config from /Users/furthur/Projects/anadea/next-lib/vite.config.ts
error during build:
ReferenceError: __filename is not defined in ES module scope
    at isFileSystemCaseSensitive (file:///Users/furthur/Projects/anadea/next-lib/node_modules/vite-plugin-dts/dist/index.mjs:11047:46)
    at getNodeSystem (file:///Users/furthur/Projects/anadea/next-lib/node_modules/vite-plugin-dts/dist/index.mjs:10812:46)
    at file:///Users/furthur/Projects/anadea/next-lib/node_modules/vite-plugin-dts/dist/index.mjs:11367:20
    at file:///Users/furthur/Projects/anadea/next-lib/node_modules/vite-plugin-dts/dist/index.mjs:11374:8
    at file:///Users/furthur/Projects/anadea/next-lib/node_modules/vite-plugin-dts/dist/index.mjs:11389:4
    at file:///Users/furthur/Projects/anadea/next-lib/node_modules/vite-plugin-dts/dist/index.mjs:172321:3
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadConfigFromBundledFile (file:///Users/furthur/Projects/anadea/next-lib/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:63495:21)
```

**Comment by qmhc** [comment]
Same to #119

**Comment by dvakatsiienko** [comment]
@qmhc great, thanks a lot
