### ISSUE TITLE
`rollupTypes: true` results in `Error: Internal Error: getResolvedModule() could not resolve module name "./myMainComponent"

### ISSUE THREAD

**Issue by jnachtigall** [qmhc/vite-plugin-dts#126]
Setting `rollupTypes: true` results in `Error: Internal Error: getResolvedModule() could not resolve module name ...`

![image](https://user-images.githubusercontent.com/3307404/195295130-255b3d57-6ffa-4838-a393-3afa9425c5ac.png)

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import dts from "vite-plugin-dts";
import { resolve } from "path";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    dts({
      insertTypesEntry: true,
      rollupTypes: true,
    }),
  ],
  build: {
    lib: {
      // Could also be a dictionary or array of multiple entry points
      entry: resolve(__dirname, "src/mainWebComponent.ts"),
      formats: ["es"],
    },
    outDir: "dist-lib",
  },
});
```

Without or commenting out ` // rollupTypes: true,` it works.

**Comment by jnachtigall** [comment]
@qmhc Same error still with version 1.6.6 

My `d.ts` file is `"types": "./dist-lib/ozgerde-vorgangsportal.d.ts",` and includes:
```ts
export * from './mainWebComponent'
```
But there is no such file in `dist-lib` 

![image](https://user-images.githubusercontent.com/3307404/195596362-bbfb35df-7a47-4939-aabd-2a20fca099c1.png)

**Comment by qmhc** [comment]
I think the cause maybe incorrect root config, would your `tsconfig.json` and project struct?

**Comment by jnachtigall** [comment]
That's my `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```
and `tsconfig.node.json`:

```json
{
  "compilerOptions": {
    "composite": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite-app.config.ts", "vite-lib.config.ts"]
}
```

Not sure, what you mean by "project struct"? It is a vite 3 structure under `modules/vgp-frontend/vite-app` and `build.outDir: "dist-lib",`

**Comment by jnachtigall** [comment]
Changing in `package.json` from 
```
  "types": "./dist-lib/ozgerde-vorgangsportal.d.ts",
```
to 
```
  "types": "./dist-lib/mainWebComponent.d.ts",
```
makes it work. 

Though now I have to files in the outputDir like this:
![image](https://user-images.githubusercontent.com/3307404/195601249-ead7bd42-b291-4f1b-aa00-9d3691dc1854.png)

That is, now there is a `ozgerde-vorgangsportal.js` and the `d.ts` file for it is *not* named after the package but is `mainWebComponent.ts` But should start like the package name `ozgerde-vorgangsportal`

**Comment by qmhc** [comment]
You add `skipDiagnostics: false` and `logDiagnostics: true` to plugin options and run build again, it there any type errors?

**Comment by jnachtigall** [comment]
Added these options, but I do not see any type errors in the output:
```bash
$ npm run buildLib

> ozgerde-vorgangsportal@1.0.0 buildLib
> tsc && vite --config vite-lib.config.ts build

vite v3.1.0 building for production...
✓ 410 modules transformed.
dist-lib/ozgerde-vorgangsportal.js   126.24 KiB / gzip: 35.05 KiB

[vite:dts] Start generate declaration files...
[vite:dts] Start rollup declaration files...
error during build:
Error: Internal Error: getResolvedModule() could not resolve module name "./mainWebComponent"
/home/jnachtigall/dev/erd/ozg-erde-formcycle/modules/vgp-frontend/vite-app/dist-lib/ozgerde-vorgangsportal.d.ts:1:1

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
    at ExportAnalyzer._fetchSpecifierAstModule (/home/jnachtigall/dev/erd/ozg-erde-formcycle/modules/vgp-frontend/vite-app/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:676:19)
    at ExportAnalyzer.fetchAstModuleFromSourceFile (/home/jnachtigall/dev/erd/ozg-erde-formcycle/modules/vgp-frontend/vite-app/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:112:65)
    at AstSymbolTable.fetchAstModuleFromWorkingPackage (/home/jnachtigall/dev/erd/ozg-erde-formcycle/modules/vgp-frontend/vite-app/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:83:37)
    at Collector.analyze (/home/jnachtigall/dev/erd/ozg-erde-formcycle/modules/vgp-frontend/vite-app/node_modules/@microsoft/api-extractor/lib/collector/Collector.js:155:51)
    at rollupDeclarationFiles (file:///home/jnachtigall/dev/erd/ozg-erde-formcycle/modules/vgp-frontend/vite-app/node_modules/vite-plugin-dts/dist/index.mjs:176858:13)
    at Object.closeBundle (file:///home/jnachtigall/dev/erd/ozg-erde-formcycle/modules/vgp-frontend/vite-app/node_modules/vite-plugin-dts/dist/index.mjs:177171:11)
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///home/jnachtigall/dev/erd/ozg-erde-formcycle/modules/vgp-frontend/vite-app/node_modules/rollup/dist/es/shared/rollup.js:22638:9)
    at async Object.close (file:///home/jnachtigall/dev/erd/ozg-erde-formcycle/modules/vgp-frontend/vite-app/node_modules/rollup/dist/es/shared/rollup.js:23709:13)
    at async Promise.all (index 0)
```

I think the build error is because within `dist-lib` there is `ozgerde-vorgangsportal.d.ts` whose content is:
```ts
export * from './mainWebComponent'
```
But in `dist-lib` there is no `mainWebComponent.ts` file. Hence it cannot be resolved. Only in `src/` this file exists

**Comment by qmhc** [comment]
Just strange, Would you mind sharing your project or provide a reproduction?

**Comment by jnachtigall** [comment]
I've set up a repo at https://github.com/jnachtigall/vite-plugin-dts-126-bug and sent you an invitation. You can toggle `rollupTypes: true` to make it work / not work.

**Comment by qmhc** [comment]
I see there is not any export in `mainWebComponent.ts`, so it will not be a module in typescript.

**Comment by qmhc** [comment]
You need to export something to make it as a moudle, such as `export default WebComponent`.
