### ISSUE TITLE
Error: The "mainEntryPointFilePath" value is not a declaration file

### ISSUE THREAD

**Issue by Tanimodori** [qmhc/vite-plugin-dts#144]
### Describe the bug

I'm using this plugin to generate dts for my cli tool `viteburner` which is in library mode and has multiple entrys (one for cli and one for importing). Previous build was success but when I try to turn on the `rollupTypes`, it will throw a error listed below:

```
PS> npm run build
> viteburner@0.4.1 build
> vite build

vite v3.2.3 building for production...
✓ 31 modules transformed.
dist/entry.js          0.38 KiB / gzip: 0.18 KiB
dist/index.js          2.43 KiB / gzip: 0.74 KiB
dist/cli.f6271bf6.js   23.61 KiB / gzip: 8.49 KiB
dist/entry.mjs          0.34 KiB / gzip: 0.17 KiB
dist/index.mjs          1.89 KiB / gzip: 0.82 KiB
dist/cli.abe6ec13.mjs   29.31 KiB / gzip: 9.16 KiB

[vite:dts] Start generate declaration files...
[vite:dts] Start rollup declaration files...
error during build:
Error: Error parsing C:\path\to\project\viteburner\api-extractor.json:
The "mainEntryPointFilePath" value is not a declaration file: C:\path\to\project\viteburner\dist\typings\entry
    at Function.prepare (C:\path\to\project\viteburner\node_modules\@microsoft\api-extractor\lib\api\ExtractorConfig.js:577:19)
    at rollupDeclarationFiles (C:\path\to\project\viteburner\node_modules\vite-plugin-dts\dist\index.cjs:176799:56)
    at Object.closeBundle (C:\path\to\project\viteburner\node_modules\vite-plugin-dts\dist\index.cjs:177200:15)
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///C:/path/to/project/viteburner/node_modules/rollup/dist/es/shared/rollup.js:22676:9)
    at async Object.close (file:///C:/path/to/project/viteburner/node_modules/rollup/dist/es/shared/rollup.js:23750:13)
    at async Promise.all (index 0)
    at async build (file:///C:/path/to/project/viteburner/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:45238:13)
    at async CAC.<anonymous> (file:///C:/path/to/project/viteburner/node_modules/vite/dist/node/cli.js:756:9)
```

Turn off `rollupTypes` in `vite.config.ts` will be fine. Any ideas?

### Reproduction

https://github.com/Tanimodori/viteburner/tree/adb6551a4e0599e914d1db23cc3c539c4b87be10

### Steps to reproduce

1. `git clone https://github.com/Tanimodori/viteburner.git`
2. `cd viteburner`
3. `git checkout adb6551a4e0599e914d1db23cc3c539c4b87be10`
4. `npm i`
5. `npm run build`

This should produce the same error above.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 7.93 GB / 15.69 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^3.2.3 => 3.2.3
    vite-plugin-dts: ^1.7.0 => 1.7.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Tanimodori** [comment]
Confirmed fixed. Thank you!
