### ISSUE TITLE
源文件有任何非ES5的symbol时无法正常rollup

### ISSUE THREAD

**Issue by KotoriK** [qmhc/vite-plugin-dts#171]
## 问题
含有WeakSet或Set成员的Class无法正常rollup
dts包含的@microsoft/api-extractor的版本是7.33.x，但是手动安装7.34.x后依然有相同的问题
## dts(option)
```ts
{ tsConfigFilePath: 'tsconfig.build.json', aliasesExclude: [/^@\//], rollupTypes: true }
```
## Log
vite v4.1.1 building for production...
✓ 1 modules transformed.
dist/problem.mjs  0.15 kB │ map: 0.33 kB

[vite:dts] Start generate declaration files...
[vite:dts] Start rollup declaration files...
error during build:
Error: Internal Error: Unable to follow symbol for "WeakSet"

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
    at AstSymbolTable._analyzeChildTree (\home\symbol-issue\node_modules\.pnpm\@microsoft+api-extractor@7.34.4\node_modules\@microsoft\api-extractor\lib\analyzer\AstSymbolTable.js:328:43)
    at AstSymbolTable._analyzeChildTree (\home\symbol-issue\node_modules\.pnpm\@microsoft+api-extractor@7.34.4\node_modules\@microsoft\api-extractor\lib\analyzer\AstSymbolTable.js:377:18)
    at AstSymbolTable._analyzeChildTree (\home\symbol-issue\node_modules\.pnpm\@microsoft+api-extractor@7.34.4\node_modules\@microsoft\api-extractor\lib\analyzer\AstSymbolTable.js:377:18)
    at AstSymbolTable._analyzeChildTree (\home\symbol-issue\node_modules\.pnpm\@microsoft+api-extractor@7.34.4\node_modules\@microsoft\api-extractor\lib\analyzer\AstSymbolTable.js:377:18)
    at AstSymbolTable._analyzeAstSymbol (\home\symbol-issue\node_modules\.pnpm\@microsoft+api-extractor@7.34.4\node_modules\@microsoft\api-extractor\lib\analyzer\AstSymbolTable.js:247:18)
    at AstSymbolTable.analyze (\home\symbol-issue\node_modules\.pnpm\@microsoft+api-extractor@7.34.4\node_modules\@microsoft\api-extractor\lib\analyzer\AstSymbolTable.js:113:25)
    at \home\symbol-issue\node_modules\.pnpm\@microsoft+api-extractor@7.34.4\node_modules\@microsoft\api-extractor\lib\analyzer\ExportAnalyzer.js:247:62
    at Map.forEach (<anonymous>)
    at ExportAnalyzer._collectAllExportsRecursive (\home\symbol-issue\node_modules\.pnpm\@microsoft+api-extractor@7.34.4\node_modules\@microsoft\api-extractor\lib\analyzer\ExportAnalyzer.js:236:48)
    at ExportAnalyzer._collectAllExportsRecursive (\home\symbol-issue\node_modules\.pnpm\@microsoft+api-extractor@7.34.4\node_modules\@microsoft\api-extractor\lib\analyzer\ExportAnalyzer.js:260:22)

### Reproduction

https://stackblitz.com/github/KotoriK/symbol-issue

### Steps to reproduce

1. pnpm install
2. pnpm run build

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    Memory: 2.97 GB / 15.35 GB 
Binaries:
    Node: 18.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.9.0 - C:\Program Files\nodejs\npm.CMD 
    pnpm: 7.22.0
npmPackages:
    vite: ^4.1.1 => 4.1.1 
    vite-plugin-dts: ^1.7.2 => 1.7.2
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You need to install `@types/node` to provide es types to typescript.

```sh
pnpm i -D @types/node
```

**Comment by KotoriK** [comment]
> You need to install `@types/node` to provide es types to typescript.
> 
> ```shell
> pnpm i -D @types/node
> ```
DOM的types不是自带的嘛，还要装```@types/node```是不是有些离谱

**Comment by qmhc** [comment]
如果你使用 TypeScript 的话它是没有自带的，需要安装。

**Comment by KotoriK** [comment]
直接用```api-extractor```的cli工具试了下，**使用默认配置，不用安装```@types/node```就能成功rollup**。
我觉得关键在于```overrideTsconfig```上。根据[文档](https://api-extractor.com/pages/configs/api-extractor_json/#compileroverridetsconfig)，```overrideTsconfig```存在时```tsconfigFilePath```会直接被忽略，因此```tsconfig.json```中的```lib```也不再生效。实际测试的结果也是如此。
