### ISSUE TITLE
TypeError [PLUGIN_ERROR]: The "path" argument must be of type string. Received an instance of Array

### ISSUE THREAD

**Issue by thisVioletHydra** [qmhc/vite-plugin-dts#176]
### Describe the bug

after update vite:dts
```q
√ [vite-aliases] - File: vite-aliases.json successfully updated                                               13:59:52
√ [vite-aliases] - Config: D:/WWW/light/tsconfig.json successfully read!                      13:59:52
√ [vite-aliases] - File: tsconfig.json successfully created                                                   13:59:52
vite v4.1.2 building for production...
transforming (21) node_modules\@intlify\shared\dist\shared.esm-bundler.js
[transform] • buildEnd
✓ 43 modules transformed.
dist/index.html                  0.52 kB
dist/assets/index-0b9ed221.css   1.92 kB │ gzip:  0.79 kB
dist/assets/index-c11fd336.js   85.55 kB │ gzip: 32.29 kB

[vite:dts] Start generate declaration files...

[transform] • closeBundle
error during build:
TypeError [PLUGIN_ERROR]: The "path" argument must be of type string. Received an instance of Array
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at resolve (node:path:171:9)
    at Object.closeBundle (file:///D:/WWW/light/node_modules/vite-plugin-dts/dist/index.mjs:888:35)
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///D:/WWW/light/node_modules/rollup/dist/es/shared/rollup.js:23819:9)
    at async Object.close (file:///D:/WWW/light/node_modules/rollup/dist/es/shared/rollup.js:25105:13)
    at async build (file:///D:/WWW/light/node_modules/vite/dist/node/chunks/dep-9912c491.js:44657:13)
    at async CAC.<anonymous> (file:///D:/WWW/light/node_modules/vite/dist/node/cli.js:813:9)
error Command failed with exit code 1.
```

### Reproduction

null

### Steps to reproduce
run `"build": "vite build --mode production",`

OLD: "[vite-plugin-dts](https://npmjs.com/package/vite-plugin-dts)": "[^1.7.3](https://npmjs.com/package/vite-plugin-dts)",
NEW  "vite-plugin-dts": "^2.0.0-beta.1",

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 17.08 GB / 31.92 GB
  Binaries:
    Node: 19.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by thisVioletHydra** [comment]
my bad
