### ISSUE TITLE
Build for a project with TypeScript 5.0 multiple extends config fails

### ISSUE THREAD

**Issue by cs-clarence** [qmhc/vite-plugin-dts#190]
### Describe the bug

If a typescript has a `tsconfig.json` that uses TS5.0 multiple config extension feature
```json5
{
  extends: [ "config1", "config2"],
  // omitted for brevity
}
```

When you try to build it, it throws the error:
```
error during build:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
    at get (https://vitejsvitejspt1j-tgbq.w-corp.staticblitz.com/blitz.811716d731bce6a23db12c75fa19a3398a6a47f2.js:6:344852)
    at <anonymous> (file:///home/projects/vitejs-vite-jspt1j/node_modules/.pnpm/vite@4.2.0/node_modules/vite/dist/node/cli.js:840:113)
 ELIFECYCLE  Command failed with exit code 1.

````

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jspt1j?file=tsconfig.json

### Steps to reproduce

`pnpm install` then `pnpm build`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vite: ^4.2.0 => 4.2.0 
    vite-plugin-dts: ^2.1.0 => 2.1.0 
```
```


### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sabasayer** [comment]
It sems in general vite-plugin-dts is not supporting typescript 5.0 .

**Comment by cs-clarence** [comment]
> It sems in general vite-plugin-dts is not supporting typescript 5.0 .

Yeah, the new options in tsconfig such as `verbatimModuleSyntax` aren't also supported
