### ISSUE TITLE
Internal Error: Unable to follow symbol for "const" when using `as const`

### ISSUE THREAD

**Issue by panvourtsis** [qmhc/vite-plugin-dts#283]
### Describe the bug

While i am using the plugin i found a problem that it cannot handle `as const` constants when passing to type.

![image](https://github.com/qmhc/vite-plugin-dts/assets/6433679/32c9729a-ddff-4486-ad22-9690977b9182)

### Reproduction

https://stackblitz.com/~/github.com/panvourtsis/react-blogs/tree/panvourtsis/showcase-as-const

### Steps to reproduce

navigate to the url that is a fork from react-blogs

I've change the `Title.tsx` with the `as const` demo prop

run `yarn build`

### System Info

```shell
[vite:dts] Internal Error: Unable to follow symbol for "const"

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
✓ built in 11.59s
error during build:
Error: Internal Error: Unable to follow symbol for "const"

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
    at new InternalError (/home/panvourtsis/react-blogs/node_modules/@rushstack/node-core-library/lib/InternalError.js:24:9)
    at AstSymbolTable._analyzeChildTree (/home/panvourtsis/react-blogs/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:328:43)
    at AstSymbolTable._analyzeChildTree (/home/panvourtsis/react-blogs/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:377:18)
    at AstSymbolTable._analyzeChildTree (/home/panvourtsis/react-blogs/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:377:18)
    at AstSymbolTable._analyzeAstSymbol (/home/panvourtsis/react-blogs/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:247:18)
    at eval (/home/panvourtsis/react-blogs/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:259:34)
    at AstDeclaration.forEachDeclarationRecursive (/home/panvourtsis/react-blogs/node_modules/@microsoft/api-extractor/lib/analyzer/AstDeclaration.js:168:9)
    at AstDeclaration.forEachDeclarationRecursive (/home/panvourtsis/react-blogs/node_modules/@microsoft/api-extractor/lib/analyzer/AstDeclaration.js:170:19)
    at AstSymbol.forEachDeclarationRecursive (/home/panvourtsis/react-blogs/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbol.js:103:28)
    at AstSymbolTable._analyzeAstSymbol (/home/panvourtsis/react-blogs/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:254:27)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Maybe a limitation of `@microsoft/api-extractor`, refer to https://github.com/microsoft/rushstack/issues/3875.

**Comment by Gengkaibo** [comment]
error during build:
[vite:dts] Internal Error: Unable to follow symbol for "const"

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
    at AstSymbolTable._analyzeChildTree (D:\Project\1-HTHT\pie-earth\node_modules\.pnpm\@microsoft+api-extractor@7.47.7_@types+node@20.16.5\node_modules\@microsoft\api-extractor\src\analyzer\AstSymbolTable.ts:406:25)    
    at AstSymbolTable._analyzeChildTree (D:\Project\1-HTHT\pie-earth\node_modules\.pnpm\@microsoft+api-extractor@7.47.7_@types+node@20.16.5\node_modules\@microsoft\api-extractor\src\analyzer\AstSymbolTable.ts:473:12)    
    at AstSymbolTable._analyzeChildTree (D:\Project\1-HTHT\pie-earth\node_modules\.pnpm\@microsoft+api-extractor@7.47.7_@types+node@20.16.5\node_modules\@microsoft\api-extractor\src\analyzer\AstSymbolTable.ts:473:12)    
    at AstSymbolTable._analyzeAstSymbol (D:\Project\1-HTHT\pie-earth\node_modules\.pnpm\@microsoft+api-extractor@7.47.7_@types+node@20.16.5\node_modules\@microsoft\api-extractor\src\analyzer\AstSymbolTable.ts:312:12)    
    at AstSymbolTable.analyze (D:\Project\1-HTHT\pie-earth\node_modules\.pnpm\@microsoft+api-extractor@7.47.7_@types+node@20.16.5\node_modules\@microsoft\api-extractor\src\analyzer\AstSymbolTable.ts:154:19)
    at D:\Project\1-HTHT\pie-earth\node_modules\.pnpm\@microsoft+api-extractor@7.47.7_@types+node@20.16.5\node_modules\@microsoft\api-extractor\src\analyzer\ExportAnalyzer.ts:340:42
    at Map.forEach (<anonymous>)
    at ExportAnalyzer._collectAllExportsRecursive (D:\Project\1-HTHT\pie-earth\node_modules\.pnpm\@microsoft+api-extractor@7.47.7_@types+node@20.16.5\node_modules\@microsoft\api-extractor\src\analyzer\ExportAnalyzer.ts:328:40)
    at ExportAnalyzer._collectAllExportsRecursive (D:\Project\1-HTHT\pie-earth\node_modules\.pnpm\@microsoft+api-extractor@7.47.7_@types+node@20.16.5\node_modules\@microsoft\api-extractor\src\analyzer\ExportAnalyzer.ts:356:14)
    at ExportAnalyzer.fetchAstModuleExportInfo (D:\Project\1-HTHT\pie-earth\node_modules\.pnpm\@microsoft+api-extractor@7.47.7_@types+node@20.16.5\node_modules\@microsoft\api-extractor\src\analyzer\ExportAnalyzer.ts:248:12)
 ELIFECYCLE  Command failed with exit code 1.
