### ISSUE TITLE
[vite:dts] Internal Error: getResolvedModule() could not resolve module name

### ISSUE THREAD

**Issue by hejtful** [qmhc/vite-plugin-dts#287]
### Describe the bug

I'm trying to bundle all type declarations into a single `index.d.ts` file.

Setting `rollupTypes: true` results in `Error: Internal Error: getResolvedModule() could not resolve module name`

```
[vite:dts] Start rollup declaration files...
Analysis will use the bundled TypeScript version 5.0.4
*** The target project appears to use TypeScript 5.2.2 which is newer than the bundled compiler engine; consider upgrading API Extractor.
[vite:dts] Internal Error: getResolvedModule() could not resolve module name "./selectors"
/Users/vitomirbudimir/serlo/frontend/dist/src/serlo-editor/store/history/index.d.ts:2:1

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
✓ built in 15.90s
error during build:
Error: Internal Error: getResolvedModule() could not resolve module name "./selectors"
/Users/vitomirbudimir/serlo/frontend/dist/src/serlo-editor/store/history/index.d.ts:2:1

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
    at ExportAnalyzer._fetchSpecifierAstModule (/Users/vitomirbudimir/serlo/frontend/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:676:19)
    at ExportAnalyzer.fetchAstModuleFromSourceFile (/Users/vitomirbudimir/serlo/frontend/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:112:65)
    at ExportAnalyzer._fetchSpecifierAstModule (/Users/vitomirbudimir/serlo/frontend/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:693:41)
    at ExportAnalyzer.fetchAstModuleFromSourceFile (/Users/vitomirbudimir/serlo/frontend/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:112:65)
    at ExportAnalyzer._fetchSpecifierAstModule (/Users/vitomirbudimir/serlo/frontend/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:693:41)
    at ExportAnalyzer._getExportOfSpecifierAstModule (/Users/vitomirbudimir/serlo/frontend/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:593:41)
    at ExportAnalyzer._tryMatchImportDeclaration (/Users/vitomirbudimir/serlo/frontend/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:518:29)
    at ExportAnalyzer.fetchReferencedAstEntity (/Users/vitomirbudimir/serlo/frontend/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:293:45)
    at AstSymbolTable._analyzeChildTree (/Users/vitomirbudimir/serlo/frontend/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:332:76)
    at AstSymbolTable._analyzeChildTree (/Users/vitomirbudimir/serlo/frontend/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:377:18)
```

Vite config: https://github.com/serlo/frontend/blob/fix/bundle-type-declarations/vite.config.ts

TS config: https://github.com/serlo/frontend/blob/fix/bundle-type-declarations/tsconfig.json

The file in whose matching type declaration file the error is thrown: https://github.com/serlo/frontend/blob/fix/bundle-type-declarations/src/serlo-editor/store/history/index.ts

The file whose type declarations seem to not be generated in time: https://github.com/serlo/frontend/blob/fix/bundle-type-declarations/src/serlo-editor/store/history/selectors.ts

### Reproduction

https://github.com/serlo/frontend/tree/fix/bundle-type-declarations

### Steps to reproduce

1. `git clone --filter=blob:none https://github.com/serlo/frontend.git`
2. `cd frontend`
3. `yarn`
4. `yarn build-editor`

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.06 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.6.1 - ~/.asdf/shims/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1
  npmPackages:
    @vitejs/plugin-react: ^4.2.0 => 4.2.0 
    vite: ^5.0.2 => 5.0.2 
    vite-plugin-dts: ^3.6.3 => 3.6.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Hi, there some diagnostic info is logged in terminal:

```log
src/serlo-editor/store/history/selectors.ts(7,14): error TS4023: Exported variable 'selectPendingChanges' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
src/serlo-editor/store/history/selectors.ts(12,14): error TS4023: Exported variable 'selectHasPendingChanges' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
src/serlo-editor/store/history/selectors.ts(17,14): error TS4023: Exported variable 'selectHasUndoActions' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
src/serlo-editor/store/history/selectors.ts(22,14): error TS4023: Exported variable 'selectHasRedoActions' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
src/serlo-editor/store/history/selectors.ts(27,14): error TS4023: Exported variable 'selectUndoStack' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
src/serlo-editor/store/history/selectors.ts(31,14): error TS4023: Exported variable 'selectRedoStack' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
src/serlo-editor/store/store.ts(12,14): error TS4023: Exported variable 'store' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
src/serlo-editor/store/store.ts(12,14): error TS4023: Exported variable 'store' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
src/serlo-editor/store/history/slice.ts(50,14): error TS4023: Exported variable 'historySlice' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
src/serlo-editor/store/history/slice.ts(50,14): error TS4023: Exported variable 'historySlice' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
src/serlo-editor/store/history/slice.ts(50,14): error TS4023: Exported variable 'historySlice' has or is using name 'HistoryState' from external module "E:/frontend/src/serlo-editor/store/types" but cannot be named.
```

They all point to the type `HistoryState` (in `<root>/src/serlo-editor/store/types.ts`) is used but cannot be named.

If a type is used on the types export chain, it needs to be export. So you should change by following:

```diff
- interface HistoryState {
+ export interface HistoryState {
  initialState?: {
    documents: State['documents']
  }
  undoStack: ReversibleAction[][]
  redoStack: ReversibleAction[][]
  pendingChanges: number
}
```

And it will build successful.

![image](https://github.com/qmhc/vite-plugin-dts/assets/40221744/d8e7ca10-7bef-428d-9cf9-ef4296ce1ef8)
