### ISSUE TITLE
Build failure on file without any declarations only scss import

### ISSUE THREAD

**Issue by hxtree** [qmhc/vite-plugin-dts#289]
### Describe the bug

A tsx file that only imports css will fail to build.

This does not build.
```
import './color-pallette.scss';
```

This does build:
```
import './color-pallette.scss';

export const HAY = '2';
```

### Reproduction

url

### Steps to reproduce

See comments

### System Info

```shell
[vite:dts] Start generate declaration files...
computing gzip size (1)...[vite:dts] Start rollup declaration files...
Analysis will use the bundled TypeScript version 5.0.4
*** The target project appears to use TypeScript 5.1.3 which is newer than the bundled compiler engine; consider upgrading API Extractor.
[vite:dts] Internal Error: Unable to determine module for: /usr/src/app/services/design-system/dist/src/ColorPallete/index.d.ts

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
✓ built in 24.13s
error during build:
Error: Internal Error: Unable to determine module for: /usr/src/app/services/design-system/dist/src/ColorPallete/index.d.ts

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
    at ExportAnalyzer._getModuleSymbolFromSourceFile (/usr/src/app/common/temp/node_modules/.pnpm/@microsoft+api-extractor@7.38.5_@types+node@20.9.0/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:168:15)
    at ExportAnalyzer.fetchAstModuleFromSourceFile (/usr/src/app/common/temp/node_modules/.pnpm/@microsoft+api-extractor@7.38.5_@types+node@20.9.0/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:69:35)
    at ExportAnalyzer._fetchSpecifierAstModule (/usr/src/app/common/temp/node_modules/.pnpm/@microsoft+api-extractor@7.38.5_@types+node@20.9.0/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:693:41)
    at ExportAnalyzer.fetchAstModuleFromSourceFile (/usr/src/app/common/temp/node_modules/.pnpm/@microsoft+api-extractor@7.38.5_@types+node@20.9.0/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:112:65)
    at AstSymbolTable.fetchAstModuleFromWorkingPackage (/usr/src/app/common/temp/node_modules/.pnpm/@microsoft+api-extractor@7.38.5_@types+node@20.9.0/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:83:37)
    at Collector.analyze (/usr/src/app/common/temp/node_modules/.pnpm/@microsoft+api-extractor@7.38.5_@types+node@20.9.0/node_modules/@microsoft/api-extractor/lib/collector/Collector.js:155:51)
    at Extractor.invoke (/usr/src/app/common/temp/node_modules/.pnpm/@microsoft+api-extractor@7.38.5_@types+node@20.9.0/node_modules/@microsoft/api-extractor/lib/api/Extractor.js:143:19)
    at rollupDeclarationFiles (/usr/src/app/common/temp/node_modules/.pnpm/vite-plugin-dts@3.6.4_@types+node@20.9.0_typescript@5.1.3_vite@5.0.5/node_modules/vite-plugin-dts/dist/index.cjs:272:41)
    at Object.writeBundle (/usr/src/app/common/temp/node_modules/.pnpm/vite-plugin-dts@3.6.4_@types+node@20.9.0_typescript@5.1.3_vite@5.0.5/node_modules/vite-plugin-dts/dist/index.cjs:933:13)
    at async Promise.all (index 0)
The script failed with exit code 1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Although without `export {}`, it does not occur any error when building.

It you thing this issue still exists, you should provide a reproduction.
