### ISSUE TITLE
The match result of alias from `paths` in `tsconfig.json` is out of bounds

### ISSUE THREAD

**Issue by antoniosZ** [qmhc/vite-plugin-dts#298]
### Describe the bug

with `3.7.0` I have no issues.

As soon as I update to `3.7.1` and try to build the project, I get the following error:

```
[vite:dts] Start generate declaration files...
dist/index.js  161.03 kB │ gzip: 43.61 kB │ map: 503.88 kB
[vite:dts] Start rollup declaration files...
Analysis will use the bundled TypeScript version 5.3.3
[vite:dts] Maximum call stack size exceeded
✓ built in 6.31s
error during build:
RangeError: Maximum call stack size exceeded
    at TypeScriptInternals.getResolvedModule (/myProject/node_modules/@microsoft/api-extractor/lib/analyzer/TypeScriptInternals.js:87:29)
    at ExportAnalyzer._isExternalModulePath (/myProject/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:196:74)
    at ExportAnalyzer._tryGetExternalModulePath (/myProject/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:654:18)
    at ExportAnalyzer._tryMatchExportDeclaration (/myProject/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:433:49)
    at ExportAnalyzer.fetchReferencedAstEntity (/myProject/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:289:45)
    at ExportAnalyzer._tryGetExportOfAstModule (/myProject/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:626:34)
    at ExportAnalyzer._getExportOfAstModule (/myProject/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:599:32)
    at ExportAnalyzer._getExportOfSpecifierAstModule (/myProject/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:594:32)
    at ExportAnalyzer._tryMatchExportDeclaration (/myProject/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:442:29)
    at ExportAnalyzer.fetchReferencedAstEntity (/myProject/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:289:45)

```

I believe it's related to https://github.com/qmhc/vite-plugin-dts/commit/e8827cb6c8be1406e4e3a9a24639b7b54ca20d53
since my project uses aliases...

### Reproduction

n/a

### System Info

```shell
System:
    OS: macOS 14.1.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 676.05 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.2.1 - ~/myProject/node_modules/.bin/npm
  Browsers:
    Chrome: 120.0.6099.234
    Edge: 100.0.1185.39
    Safari: 17.1.2
  npmPackages:
    vite: ^5.0.11 => 5.0.11
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Please provide a reproduction.

**Comment by antoniosZ** [comment]
@qmhc ok, I will try to provide one

**Comment by antoniosZ** [comment]
it appears that it tries to resolve the import `MyConfig` within the `./src/myTypes/index` into `./src/myTypes/index` and thus, causes an infinite recursion of path resolution...
