### ISSUE TITLE
[vite:dts] Internal Error when re-exporting types from index.js

### ISSUE THREAD

**Issue by Undistraction** [qmhc/vite-plugin-dts#358]
### Describe the bug

I have all my types in `src/types.ts` and in order for them to be rolled up into a single file it looks like I need to re-export them from `src/index.js`. I do that with:
```
export * from './types'
```

This results in the following error on build:

```
x Build failed in 810ms
error during build:
[vite:dts] Internal Error: getResolvedModule() could not resolve module name "./types"
/Users/pedr/Documents/Code/Repositories/coons-patch/dist/index.d.ts:124:1

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
    at ExportAnalyzer._fetchSpecifierAstModule (/Users/pedr/Documents/Code/Repositories/coons-patch/node_modules/.pnpm/@microsoft+api-extractor@7.47.4_@types+node@20.14.10/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:688:19)
    at ExportAnalyzer.fetchAstModuleFromSourceFile (/Users/pedr/Documents/Code/Repositories/coons-patch/node_modules/.pnpm/@microsoft+api-extractor@7.47.4_@types+node@20.14.10/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:113:65)
    at AstSymbolTable.fetchAstModuleFromWorkingPackage (/Users/pedr/Documents/Code/Repositories/coons-patch/node_modules/.pnpm/@microsoft+api-extractor@7.47.4_@types+node@20.14.10/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:83:37)
    at Collector.analyze (/Users/pedr/Documents/Code/Repositories/coons-patch/node_modules/.pnpm/@microsoft+api-extractor@7.47.4_@types+node@20.14.10/node_modules/@microsoft/api-extractor/lib/collector/Collector.js:205:51)
    at Extractor.invoke (/Users/pedr/Documents/Code/Repositories/coons-patch/node_modules/.pnpm/@microsoft+api-extractor@7.47.4_@types+node@20.14.10/node_modules/@microsoft/api-extractor/lib/api/Extractor.js:144:19)
    at rollupDeclarationFiles (file:///Users/pedr/Documents/Code/Repositories/coons-patch/node_modules/.pnpm/vite-plugin-dts@4.0.0-beta.2_@types+node@20.14.10_rollup@4.18.0_typescript@5.4.2_vite@5.3.3_@types+node@20.14.10_/node_modules/vite-plugin-dts/dist/index.mjs:354:20)
    at rollup (file:///Users/pedr/Documents/Code/Repositories/coons-patch/node_modules/.pnpm/vite-plugin-dts@4.0.0-beta.2_@types+node@20.14.10_rollup@4.18.0_typescript@5.4.2_vite@5.3.3_@types+node@20.14.10_/node_modules/vite-plugin-dts/dist/index.mjs:1129:28)
    at Object.writeBundle (file:///Users/pedr/Documents/Code/Repositories/coons-patch/node_modules/.pnpm/vite-plugin-dts@4.0.0-beta.2_@types+node@20.14.10_rollup@4.18.0_typescript@5.4.2_vite@5.3.3_@types+node@20.14.10_/node_modules/vite-plugin-dts/dist/index.mjs:1151:19)
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///Users/pedr/Documents/Code/Repositories/coons-patch/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:19702:9)
 ELIFECYCLE  Command failed with exit code 1.
```

vite.config.js:
```
export default defineConfig(() => {
  return {
    logLevel: 'info',
    build: {
      minify: false,
      sourcemap: true,
      lib: {
        entry: resolve(__dirname, 'src/index.ts'),
        name: 'Coons Patch',
        formats: ['es', 'cjs'],
        // Choose names for build artifacts
        fileName: (format) => {
          if (format === 'es') {
            return 'index.mjs'
          }
          if (format === 'cjs') {
            return 'index.common.js'
          }
        },
      },
    },
    plugins: [
      // Generate a single types file for all our types
      dts({
        rollupTypes: true,
      }),
    ],
  }
})
```

tsconfig.js
```
{
  "include": ["src/**/*"],
  "compilerOptions": {
    "module": "preserve",
    "moduleResolution": "bundler",
    "target": "ES2020",
    "sourceMap": true,
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "useUnknownInCatchVariables": false,
    "typeRoots": ["./src/@types", "./node_modules/@types"],
    "declaration": true,
    "declarationDir": "./dist"
  }
}
```

### Reproduction

https://github.com/Undistraction/coons-patch/tree/bug/vite-plugin-dts

### Steps to reproduce

- `pnpm install`
- `pnpm run build`

Note that if you remove the re-export from the bottom of `src/index.ts` the build completes successfully. 

I've tried both `3.x` and the `4.x` beta versions and both share the same error. 

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 1.05 GB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.74
    Edge: 127.0.2651.74
    Safari: 17.4.1
  npmPackages:
    vite: ^5.3.3 => 5.3.3 
    vite-plugin-dts: 4.0.0-beta.2 => 4.0.0-beta.2
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Undistraction** [comment]
Did some more digging. If I try and re-export the types individually, that fails with a different error:
```
export { Column } from './types'
```
Error:
```
src/index.ts (21:9): "Column" is not exported by "src/types.ts", imported by "src/index.ts".
```

However if export an enum from the same file and re-export that, there is no error, so it seems related to exports that are `type` or `interface`.

**Comment by Undistraction** [comment]
Workaround is to remove `rollupTypes: true,`, move all types to `types.ts` and re-export  that in `index.ts`:
```
export * from './types'
```

**Comment by qmhc** [comment]
I cloned the reproduction and run build, but get no error. Is something changed?

**Comment by Undistraction** [comment]
@qmhc I'm really sorry about that. It's on a specific branch:
```
git clone -b bug/vite-plugin-dts https://github.com/Undistraction/coons-patch.git
cd coons-patch
pnpm install
pnpm build
```

I've just run through the above and verified that get's you the correct error.

**Comment by qmhc** [comment]
It seems still an error when export an enum in `types.d.ts`.

**Comment by qmhc** [comment]
It seems `@microsoft/api-extractor` does not support `"module": "preserve"`, you can change to `"module": "ESNext"` as a workaround.

**Comment by Undistraction** [comment]
@qmhc thanks for digging into that. Seems like an upstream limitation so happy to close this. However `preserve` is one of the options recommended in the TS docs, so probably worth mentioning this limitation in the README.

**Comment by barbara-b-boechat-sh3** [comment]
I'm having a similar issue... in this point I'm not using rollup anymore just to see what was being generated. But my problem is really similar I guess

The error is: 

`error TS6305: Output file '{...}/components/dist/types/src/utils/index.d.ts' has not been built from source file '{...}/components/src/utils/index.ts'.

33 export * from "./utils";
                 ~~~~~~~~~
`

my tsconfig `tsconfig.app.json`

`    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    "sourceMap": true,
    "resolveJsonModule": true,
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "experimentalDecorators": true,
    "declarationDir": "./dist/types",
    "types": [
      "vite/client"
    ],
    "allowJs": true,
    // Generate d.ts files
    "declaration": true,`

and my tsconfig.node.json 

`  "composite": true,
    "noEmit": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.node.tsbuildinfo",

    // "module": "ESNext",
    "module": "Preserve",
    "moduleResolution": "Bundler",
    "declaration": true,
    "types": ["node"],
`

I tried as you said @qmhc to change from `preserve` to `esnext` but it didn't really work out. And also used the tsconfig.build.json solution that you pointed in other issues and did some resolution but not the all the problems were resolved at this point.
