### ISSUE TITLE
request for supporting apiReport.reportVariants

### ISSUE THREAD

**Issue by yuzheng14** [qmhc/vite-plugin-dts#371]
### Description

see: https://api-extractor.com/pages/configs/api-extractor_json/#apireportreportvariants

I want to bundle some api signed `internal` etc to be bundled, but I can't in this in type `PluginOptions`.

I find that the `rollupConfig` has the similar field `apiReport`, but I doesn't have `reportVariants` fields on type, and I try to configure like following:

```typescript
    dts({
      rollupTypes: true,
      rollupConfig: {
        apiReport: {
          // @ts-expect-error - @microsoft/api-extractor 没暴露出来这个配置
          reportVariants: ['complete'],
        },
      },
    }),
```

It reports:

```
x Build failed in 562ms
error during build:
[vite:dts] JSON validation failed:
/Users/yuzheng14/code/repositories/msun-lib-suivant/packages/common/api-extractor.json

Error: #/apiReport (Configures how the API report file (*...)
       Additional properties not allowed: reportVariants
    at /Users/yuzheng14/code/repositories/msun-lib-suivant/node_modules/.pnpm/@rushstack+node-core-library@4.0.2_@types+node@20.12.12/node_modules/@rushstack/node-core-library/lib/JsonSchema.js:193:19
    at JsonSchema.validateObjectWithCallback (/Users/yuzheng14/code/repositories/msun-lib-suivant/node_modules/.pnpm/@rushstack+node-core-library@4.0.2_@types+node@20.12.12/node_modules/@rushstack/node-core-library/lib/JsonSchema.js:207:13)
    at JsonSchema.validateObject (/Users/yuzheng14/code/repositories/msun-lib-suivant/node_modules/.pnpm/@rushstack+node-core-library@4.0.2_@types+node@20.12.12/node_modules/@rushstack/node-core-library/lib/JsonSchema.js:191:14)
    at ExtractorConfig.prepare (/Users/yuzheng14/code/repositories/msun-lib-suivant/node_modules/.pnpm/@microsoft+api-extractor@7.43.0_@types+node@20.12.12/node_modules/@microsoft/api-extractor/lib/api/ExtractorConfig.js:355:36)
    at rollupDeclarationFiles (file:///Users/yuzheng14/code/repositories/msun-lib-suivant/node_modules/.pnpm/vite-plugin-dts@3.9.1_@types+node@20.12.12_rollup@4.18.0_typescript@5.4.5_vite@5.3.1_@types+n_2di4uko7rs5m3ulo7irf4xfzja/node_modules/vite-plugin-dts/dist/index.mjs:261:43)
    at rollup (file:///Users/yuzheng14/code/repositories/msun-lib-suivant/node_modules/.pnpm/vite-plugin-dts@3.9.1_@types+node@20.12.12_rollup@4.18.0_typescript@5.4.5_vite@5.3.1_@types+n_2di4uko7rs5m3ulo7irf4xfzja/node_modules/vite-plugin-dts/dist/index.mjs:1035:28)
    at Object.writeBundle (file:///Users/yuzheng14/code/repositories/msun-lib-suivant/node_modules/.pnpm/vite-plugin-dts@3.9.1_@types+node@20.12.12_rollup@4.18.0_typescript@5.4.5_vite@5.3.1_@types+n_2di4uko7rs5m3ulo7irf4xfzja/node_modules/vite-plugin-dts/dist/index.mjs:1057:19)
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///Users/yuzheng14/code/repositories/msun-lib-suivant/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:19702:9)
    at async file:///Users/yuzheng14/code/repositories/msun-lib-suivant/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:20699:13
```

### Suggested solution

I don't know it's the problem of `vite-plugin-dts` or `@microsoft/api-extractor` so that I don't know where should be modified.

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
<img width="276" alt="image" src="https://github.com/user-attachments/assets/fee2f232-b5ba-4534-976d-62c6261fe2ec">
<img width="642" alt="image" src="https://github.com/user-attachments/assets/937ff6f2-8f3e-4436-9230-e8f6403ba20a">

Maybe you can provide a reproduction.
