### ISSUE TITLE
[Bug] The argument 'path' must be a string or Uint8Array without null bytes

### ISSUE THREAD

**Issue by harrytran998** [qmhc/vite-plugin-dts#47]
Hi, thanks you @qmhc  for great library! But today I had an error when I use this lib with `yarn 3 pnp`!

<summary>
<details>

```
[vite:dts] The argument 'path' must be a string or Uint8Array without null bytes. Received '/home/techmely/techmely/packages/utils/\x00commonjsHelpers.js'
file: commonjsHelpers.js
error during build:
TypeError [PLUGIN_ERROR]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/home/techmely/techmely/packages/utils/\x00commonjsHelpers.js'
    at Object.openSync (node:fs:577:10)
    at NodeFS.openSync (/home/techmely/techmely/.pnp.cjs:14347:24)
    at makeCallSync.subPath.subPath (/home/techmely/techmely/.pnp.cjs:17033:26)
    at ZipOpenFS.makeCallSync (/home/techmely/techmely/.pnp.cjs:17789:26)
    at ZipOpenFS.openSync (/home/techmely/techmely/.pnp.cjs:17032:17)
    at VirtualFS.openSync (/home/techmely/techmely/.pnp.cjs:14785:24)
    at PosixFS.openSync (/home/techmely/techmely/.pnp.cjs:14785:24)
    at URLFS.openSync (/home/techmely/techmely/.pnp.cjs:14785:24)
    at Object.readFileSync (node:fs:453:35)
    at NodeFS.readFileSync (/home/techmely/techmely/.pnp.cjs:14693:24)
    
```
</details>
</summary>

Reproduction:
The repo [`https://github.com/techmely/techmely/blob/main/packages/utils/vite.config.ts`](https://github.com/techmely/techmely/blob/main/packages/utils/vite.config.ts)

You can check the error with the command: `yarn build:utils`

Hope you or someone can fix that <3

**Comment by qmhc** [comment]
Sorry for belated reply (due to the heavy work recently).

This reproduction link takes 404 status, and I see this project is switched to `pnpm`.

I have cloned this project and run `pnpm i`, but I get following error during processing and fail:

```sh
node_modules/.pnpm/iltorb@2.4.5/node_modules/iltorb: Running install script, failed in 4.8s
.../iltorb@2.4.5/node_modules/iltorb install$ node ./scripts/install.js || node-gyp rebuild
```

Is some new reproduction steps?

**Comment by harrytran998** [comment]
Thank you for your reply, but I currently do not use this plugin anymore! So I close it, Merry Christmas <3!
