### ISSUE TITLE
A new update is breaking bundling of SSR application

### ISSUE THREAD

**Issue by sionzee** [qmhc/vite-plugin-dts#61]
Hello,

on update to 1.0.0 the DTS is breaking bundling of `chalk`,

```
failed to load config from /home/sionzee/projects/censured/editor/packages/editor/vite.config.ts
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/sionzee/projects/censured/editor/node_modules/.pnpm/chalk@5.0.1/node_modules/chalk/source/index.js from /home/sionzee/projects/censured/editor/node_modules/.pnpm/vite-plugin-dts@1.0.0_vite@2.8.6/node_modules/vite-plugin-dts/dist/index.js not supported.
Instead change the require of /home/sionzee/projects/censured/editor/node_modules/.pnpm/chalk@5.0.1/node_modules/chalk/source/index.js in /home/sionzee/projects/censured/editor/node_modules/.pnpm/vite-plugin-dts@1.0.0_vite@2.8.6/node_modules/vite-plugin-dts/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/sionzee/projects/censured/editor/node_modules/.pnpm/vite-plugin-dts@1.0.0_vite@2.8.6/node_modules/vite-plugin-dts/dist/index.js:34:28)
    at async Promise.all (index 0)
    at async loadConfigFromFile (/home/sionzee/projects/censured/editor/node_modules/.pnpm/vite@2.8.6/node_modules/vite/dist/node/chunks/dep-9c153816.js:71326:31)
    at async resolveConfig (/home/sionzee/projects/censured/editor/node_modules/.pnpm/vite@2.8.6/node_modules/vite/dist/node/chunks/dep-9c153816.js:70873:28)
    at async createServer (/home/sionzee/projects/censured/editor/node_modules/.pnpm/vite@2.8.6/node_modules/vite/dist/node/chunks/dep-9c153816.js:56425:20)
    at async CAC.<anonymous> (/home/sionzee/projects/censured/editor/node_modules/.pnpm/vite@2.8.6/node_modules/vite/dist/node/cli.js:688:24)
undefined
```

Returning back to ^0.9.10 fixes the error.

----

This looks like an include issue, because it is visiting node_modules of other packages in monorepo.
I'm using chalk in package where `vite-plugin-dts` is not included.

In the config I have:
```
    plugins: [
      dts({
        include: ['./index.ts', './src'],
      })
    ],
```

Unfortunately I cannot provide source code due NDA.

**Comment by sionzee** [comment]
I was just testing it and it works! 🎉 Thank you for quick fix.
