### ISSUE TITLE
Missing parser plugins causes build process fail when using vue@3.3.26+

### ISSUE THREAD

**Issue by aohanhe** [qmhc/vite-plugin-dts#78]
当我把我的vue版本改为3.2.36时,vite-plugin-dts,在build以下代码：就会出现错误
    `export type FormStateContainerInstance = ComponentPublicInstance<
    formStatePropsDefine,
    {},
    {},
    {},
    formStateContanerMethodDefine
  >`
错误为: SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): "flow", "typescript". (23:9)

**Comment by qmhc** [comment]
你指的是将该插件的项目的 `vue` 的依赖改为 `3.2.36` 进行打包报错，还是你自己的项目的 `vue` 的依赖改为 `3.2.36` 并用了插件后，打包报错？

**Comment by zybieku** [comment]
+1

**Comment by zybieku** [comment]
![image](https://user-images.githubusercontent.com/15903330/173757050-86b2249b-93a3-41b1-bd08-8bdb5243a62a.png)

**Comment by qmhc** [comment]
我在 vue@3.2.37 下测试并没有问题，或许你需要提供一个复现。

![image](https://user-images.githubusercontent.com/40221744/174117576-1950dfeb-3c86-44ed-9117-8d02b5525b31.png)

**Comment by richard1015** [comment]
> 我在 vue@3.2.37 下测试并没有问题，或许你需要提供一个复现。
> 
> ![image](https://user-images.githubusercontent.com/40221744/174117576-1950dfeb-3c86-44ed-9117-8d02b5525b31.png)

https://github.com/jdf2e/nutui

使用我们仓库 安装依赖 npm  run build 即可复现

**Comment by richard1015** [comment]
3.2.37也报错

**Comment by qmhc** [comment]
@richard1015 我拉下来之后本地用各种包管理器安装都会在一个 `node-pre-gyp` 相关的东西上出错导致失败。

**Comment by Preyou** [comment]
见鬼，我也遇到这个错误了

**Comment by Preyou** [comment]
> 

https://e.coding.net/preyou/vue-design-ts/vue-design-ts.git

使用git克隆后，依次运行 `cnpm i `, `cnpm run build`即可复现错误
```sh
> Executing task: npm run build <


> vue-design-ts@0.0.0 build
> vite build && vue-tsc --declaration --emitDeclarationOnly -p tsconfig.build.json

vite v2.9.13 building for production...
✓ 1 modules transformed.

[vite:dts] Start generate declaration files...
[vite:dts] Declaration files built in 9419ms.

[vite:dts] This experimental syntax requires enabling one of the following parser plugin(s): "flow", "typescript". (5:7)
file: C:/Users/欧阳文虎/Desktop/新建文件夹/vue-design-ts/src/lib/components/popup/PopUp.vue:5:7
error during build:
SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): "flow", "typescript". (5:7)
    at instantiate (C:\Users\欧阳文虎\Desktop\新建文件夹\vue-design-ts\node_modules\_@babel_parser@7.18.6@@babel\parser\lib\index.js:72:32)
    at constructor (C:\Users\欧阳文虎\Desktop\新建文件夹\vue-design-ts\node_modules\_@babel_parser@7.18.6@@babel\parser\lib\index.js:359:12)
    at Parser.raise (C:\Users\欧阳文虎\Desktop\新建文件夹\vue-design-ts\node_modules\_@babel_parser@7.18.6@@babel\parser\lib\index.js:3339:19)
    at Parser.expectOnePlugin (C:\Users\欧阳文虎\Desktop\新建文件夹\vue-design-ts\node_modules\_@babel_parser@7.18.6@@babel\parser\lib\index.js:3396:18)    
    at Parser.isExportDefaultSpecifier (C:\Users\欧阳文虎\Desktop\新建文件夹\vue-design-ts\node_modules\_@babel_parser@7.18.6@@babel\parser\lib\index.js:16042:16)
    at Parser.maybeParseExportDefaultSpecifier (C:\Users\欧阳文虎\Desktop\新建文件夹\vue-design-ts\node_modules\_@babel_parser@7.18.6@@babel\parser\lib\index.js:15918:14)
    at Parser.parseExport (C:\Users\欧阳文虎\Desktop\新建文件夹\vue-design-ts\node_modules\_@babel_parser@7.18.6@@babel\parser\lib\index.js:15871:29)       
    at Parser.parseStatementContent (C:\Users\欧阳文虎\Desktop\新建文件夹\vue-design-ts\node_modules\_@babel_parser@7.18.6@@babel\parser\lib\index.js:14759:27)
    at Parser.parseStatement (C:\Users\欧阳文虎\Desktop\新建文件夹\vue-design-ts\node_modules\_@babel_parser@7.18.6@@babel\parser\lib\index.js:14643:17)    
    at Parser.parseBlockOrModuleBlockBody (C:\Users\欧阳文虎\Desktop\新建文件 夹\vue-design-ts\node_modules\_@babel_parser@7.18.6@@babel\parser\lib\index.js:15286:25)
终端进程“C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run build”已终止，退出代码: 1。

终端将被任务重用，按任意键关闭。
```

**Comment by Preyou** [comment]
> 需要一个复现的仓库以及复现步骤

**Comment by Preyou** [comment]
> 需要一个复现的仓库以及复现步骤

你好，我给的例子能复现吗？
这个仓库过段时间会更新，所以麻烦尽快clone

**Comment by qmhc** [comment]
> > 需要一个复现的仓库以及复现步骤
> 
> 你好，我给的例子能复现吗？ 这个仓库过段时间会更新，所以麻烦尽快clone

我这边登陆之后，打开依旧无限提示未登录然后跳转到登录页，我无法访问到这个仓库

**Comment by Preyou** [comment]
> > > 需要一个复现的仓库以及复现步骤
> > 
> > 
> > 你好，我给的例子能复现吗？ 这个仓库过段时间会更新，所以麻烦尽快clone
> 
> 我这边登陆之后，打开依旧无限提示未登录然后跳转到登录页，我无法访问到这个仓库

我现在把仓库同步到了github
https://github.com/Preyou/vue-design-ts.git
